version: 2.1
executors:
  frontend:
    docker:
      - image: cimg/node:14.15.1
    working_directory: ~/hhp/frontend
jobs:
  build:
    executor:
      frontend
    steps:
      - checkout:
          path: ~/hhp
      - run: ls
      - run: npm install
      - run: npm run build 
      - save_cache:
          key: dependency-cache
          paths:
            - node_modules
  test:
    executor:
      frontend
    steps:
      - checkout:
          path: ~/hhp
      - restore_cache:
          key: dependency-cache
      - run: npm run test
workflows:
  node-tests:
    jobs:
      - build
      - test:
          requires:
          - build
