version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  coverage:
    docker:
      - image: cimg/node:14.15.1
    steps:
      - checkout
      - run: 
          command: npm install
          working_directory: './frontend'
      - run:
          name: "Run Jest and Collect Coverage Reports"
          command: jest --collectCoverage=true
          working_directory: './frontend'
      - store_artifacts:
          path: frontend/coverage
workflows:
  node-tests:
    jobs:
      - node/test:
          app-dir: './frontend'
      - coverage