version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  coverage:
    docker:
      - image: cimg/node:14.15.1
    steps:
      - restore_cache:
          keys:
            - node-deps-v1
      - run:
          name: "Run Jest and Collect Coverage Reports"
          command: jest --collectCoverage=true
      - store_artifacts:
          path: coverage
workflows:
  node-tests:
    jobs:
      - node/test:
          app-dir: './frontend'
      - coverage:
          requires: 
            - node/test