version: 2.1
executors:
  frontend:
    docker:
      - image: cimg/node:14.15.1
jobs:
  build:
    executor:
      frontend
    steps:
      - checkout
      - run: next build
  test:
    executor:
      frontend
    steps:
      - node/test
workflows:
  node-tests:
    jobs:
      - build
      - test:
          requires:
          - build